export const KEYWORD_DOCS: Record<string, string> = {
  template: `### \`template\`\nDefines a reusable component template structure.\n\n**Required Elements:** \`TemplateName | (parameters)\`\n\n**Example:**\n\`\`\`declare\ntemplate Star(color) {\n  group {\n    circle { radius: 10, color: color }\n  }\n}\n\`\`\``,
  use: `### \`use\`\nInstantiates a template into the scene.\n\n**Required Elements:** \`TemplateName | (arguments) | instanceName\`\n\n**Example:**\n\`\`\`declare\nuse Star(#ef4444) myStar {\n  position: (100, 100)\n  scale: 1.5\n}\n\`\`\``,
  generate: `### \`generate\`\nCreates a loop to generate multiple objects or groups. The loop variable can be used in math expressions inside the block.\n\n**Required Elements:** \`variable | from | startValue | to | endValue\`\n\n**Example:**\n\`\`\`declare\ngenerate i from 1 to 5 {\n  circle dot {\n    position: (i * 50, 100)\n    radius: 10\n  }\n}\n\`\`\``,
  def: `### \`def\`\nDeclares a constant variable. Variables in Declare are strictly block-scoped and immutable.\n\n**Required Elements:** \`variableName | = | value\`\n\n**Example:**\n\`\`\`declare\ndef spacing = 50\n\`\`\``,
  sequence: `### \`sequence\`\nA timeline block that executes its child \`animate\` or \`physics\` steps in exact order.\n\n**Required Elements:** \`animate\`, \`physics\`, or \`parallel\` child blocks\n\n**Example:**\n\`\`\`declare\nsequence {\n  animate {\n    property: alpha\n    to: 0.0\n    duration: 0.4\n    easing: easeIn\n  }\n}\n\`\`\``,
  parallel: `### \`parallel\`\nA wrapper that explicitly groups multiple \`animate\` or \`physics\` steps to execute simultaneously. It can *only* be used inside a \`sequence\` block.\n\n**Required Elements:** \`animate\` or \`physics\` child blocks\n\n**Example:**\n\`\`\`declare\nparallel {\n  animate { property: scale, to: 2.0, duration: 1.0 }\n  animate { property: alpha, to: 0.0, duration: 1.0 }\n}\n\`\`\``,
  scene: `### \`scene\`\nThe root block of a Declare program. Contains all objects and global scene properties.\n\n**Required Properties:** \`size\`\n\n**Optional Properties:** \`background | sceneFit\`\n\n**Example:**\n\`\`\`declare\nscene {\n  size: (800, 600)\n  background: #080811\n  sceneFit: contain\n}\n\`\`\``,
  circle: `### \`circle\`\nA renderable circle object.\n\n**Required Properties:** \`position | radius\`\n\n**Optional Properties:** \`color | alpha | rotation | scale | z\`\n\n**Example:**\n\`\`\`declare\ncircle myCircle {\n  position: (400, 300)\n  radius: 50\n  color: #38bdf8\n  alpha: 0.8\n  rotation: 45\n  scale: (1.5, 1.5)\n  z: 10\n}\n\`\`\``,
  rectangle: `### \`rectangle\`\nA renderable rectangle object.\n\n**Required Properties:** \`position | size\`\n\n**Optional Properties:** \`color | alpha | rotation | scale | z\`\n\n**Example:**\n\`\`\`declare\nrectangle myRect {\n  position: (100, 100)\n  size: (200, 150)\n  color: #4ade80\n  alpha: 1.0\n  rotation: 0\n  scale: 1.0\n  z: 5\n}\n\`\`\``,
  polygon: `### \`polygon\`\nA renderable polygon object formed by a list of points.\n\n**Required Properties:** \`points\`\n\n**Optional Properties:** \`position | color | alpha | rotation | scale | z\`\n\n**Example:**\n\`\`\`declare\npolygon myPoly {\n  position: (0, 0)\n  points: [(50,0), (100,100), (0,100)]\n  color: #a78bfa\n  alpha: 0.9\n  rotation: 180\n  scale: 2.0\n  z: 2\n}\n\`\`\``,
  line: `### \`line\`\nA renderable line object connecting a list of points.\n\n**Required Properties:** \`position | points | thickness\`\n\n**Optional Properties:** \`color | alpha | rotation | scale | z\`\n\n**Example:**\n\`\`\`declare\nline myLine {\n  position: (0, 0)\n  points: [(10,10), (200,10), (200,200)]\n  thickness: 4\n  color: #f87171\n  alpha: 1.0\n  rotation: 0\n  scale: 1.0\n  z: 1\n}\n\`\`\``,
  text: `### \`text\`\nA renderable text object.\n\n**Required Properties:** \`position | content\`\n\n**Optional Properties:** \`fontSize | color | alpha | rotation | scale | z\`\n\n**Example:**\n\`\`\`declare\ntext myText {\n  position: (400, 300)\n  content: "Declare UI"\n  fontSize: 24\n  color: #f8fafc\n  alpha: 1.0\n  rotation: 0\n  scale: 1.0\n  z: 10\n}\n\`\`\``,
  group: `### \`group\`\nA container object that groups multiple child objects together.\n\n**Optional Properties:** \`position | rotation | scale | alpha | z\`\n\n**Example:**\n\`\`\`declare\ngroup myGroup {\n  position: (100, 100)\n  rotation: 45\n  scale: (1.5, 1.5)\n  alpha: 0.8\n  z: 5\n\n  circle {\n    position: (0, 0)\n    radius: 20\n  }\n}\n\`\`\``,
  physics: `### \`physics\`\nA block that applies a 2D physics simulation to its parent object.\n\n**Required Properties:** \`duration\`\n\n**Optional Properties:** \`velocity | gravity | airDrag | bounce | collideBounds\`\n\n**Example:**\n\`\`\`declare\nphysics {\n  duration: indefinitely\n  velocity: (200, -500)\n  gravity: (0, 980)\n  airDrag: 0.02\n  bounce: 0.65\n  collideBounds: true\n}\n\`\`\``,
  animate: `### \`animate\`\nA block that animates a specific property of its parent object over time.\n\n**Required Properties:** \`property | to | duration\`\n\n**Optional Properties:** \`easing | loop | yoyo | handOff\`\n\n**Example:**\n\`\`\`declare\nanimate {\n  property: position\n  to: (500, 300)\n  duration: 2.5\n  easing: easeInOut\n  loop: true\n  yoyo: true\n  handOff: false\n}\n\`\`\``,
};

export const PROPERTY_DOCS: Record<string, string> = {
  position:      `### \`position\`\nSets the \`(x, y)\` coordinates of the object's geometric center in the scene.\n\n**Accepts:** \`point\`\n**Example:** \`position: (100, 200)\``,
  radius:        `### \`radius\`\nSets the radius of a circle.\n\n**Accepts:** \`number\` (greater than 0)\n**Example:** \`radius: 50\``,
  size:          `### \`size\`\nSets the width and height of a rectangle or the scene.\n\n**Accepts:** \`point\` (width, height)\n**Example:** \`size: (600, 400)\``,
  points:        `### \`points\`\nDefines the vertices of a polygon or line.\n\n**Accepts:** \`pointList\`\n**Example:** \`points: [(0,0), (100,0), (50,100)]\``,
  thickness:     `### \`thickness\`\nSets the stroke width in pixels for a line.\n\n**Accepts:** \`number\` (greater than 0)\n**Example:** \`thickness: 4\``,
  content:       `### \`content\`\nThe text string to display.\n\n**Accepts:** \`string\`\n**Example:** \`content: "Hello World"\``,
  fontSize:      `### \`fontSize\`\nThe size of the text font.\n\n**Accepts:** \`number\`\n**Example:** \`fontSize: 24\``,
  color:         `### \`color\`\nThe fill color. Can be a named color or a hex code.\n\n**Accepts:** \`color\`\n**Example:** \`color: red\` or \`color: #ff0000\``,
  alpha:         `### \`alpha\`\nTransparency level from \`0.0\` (invisible) to \`1.0\` (fully opaque).\n\n**Accepts:** \`number\`\n**Example:** \`alpha: 0.5\``,
  rotation:      `### \`rotation\`\nRotation angle in degrees.\n\n**Accepts:** \`number\`\n**Example:** \`rotation: 45\``,
  scale:         `### \`scale\`\nScales the object. Can be a uniform number or a point for independent X/Y scaling.\n\n**Accepts:** \`number\` or \`point\`\n**Example:** \`scale: 1.5\` or \`scale: (2, 0.5)\``,
  z:             `### \`z\`\nZ-index for rendering order. Objects with higher \`z\` values are drawn on top.\n\n**Accepts:** \`number\`\n**Example:** \`z: 10\``,
  background:    `### \`background\`\nThe background color of the scene.\n\n**Accepts:** \`color\`\n**Example:** \`background: #222222\``,
  sceneFit:      `### \`sceneFit\`\nHow the scene scales to the preview window.\n\n**Accepts:** \`contain\`, \`cover\`, \`fill\`, or \`none\`\n**Example:** \`sceneFit: contain\``,
  property:      `### \`property\`\nThe specific property targeted by the animation block.\n\n**Accepts:** \`position\`, \`rotation\`, \`scale\`, \`alpha\`\n**Example:** \`property: rotation\``,
  to:            `### \`to\`\nThe target value for the animation.\n\n**Example:** \`to: 360\``,
  duration:      `### \`duration\`\nHow long the animation or physics simulation runs in seconds. For top-level \`physics\` blocks (not inside a \`sequence\`), you may also use the keyword \`indefinitely\` to run forever.\n\n**Accepts:** \`number\` or \`indefinitely\` (physics only, outside sequence)\n**Example:** \`duration: 2.5\` or \`duration: indefinitely\``,
  easing:        `### \`easing\`\nThe rate of change over time.\n\n**Accepts:** \`linear\`, \`easeIn\`, \`easeOut\`, \`easeInOut\`\n**Example:** \`easing: easeInOut\``,
  loop:          `### \`loop\`\nWhether the animation repeats endlessly.\n\n**Accepts:** \`true\`, \`false\`\n**Example:** \`loop: true\``,
  yoyo:          `### \`yoyo\`\nWhether the animation smoothly reverses back to its starting position at the end of its duration.\n\n**Accepts:** \`true\`, \`false\`\n**Example:** \`yoyo: true\``,
  handOff:       `### \`handOff\`\nAllows an animation to seamlessly transfer its final momentum to the physics engine once completed. Requires a sibling \`physics\` block.\n\n**Accepts:** \`true\`, \`false\`\n**Example:** \`handOff: true\``,
  velocity:      `### \`velocity\`\nThe initial momentum vector of the object in pixels per second.\n\n**Accepts:** \`point\`\n**Example:** \`velocity: (200, -500)\``,
  gravity:       `### \`gravity\`\nThe continuous acceleration applied each frame. \`(0, 980)\` mimics real-world downward gravity.\n\n**Accepts:** \`point\`\n**Example:** \`gravity: (0, 980)\``,
  airDrag:       `### \`airDrag\`\nThe frame-rate independent drag coefficient between \`0.0\` and \`1.0\`. \`0.0\` means no air drag (vacuum). Higher values increase resistance.\n\n**Accepts:** \`number\`\n**Example:** \`airDrag: 0.02\``,
  bounce:        `### \`bounce\`\nThe restitution coefficient when colliding with a boundary, mapping \`0.0\` (no bounce) to \`1.0\` (perfectly elastic).\n\n**Accepts:** \`number\`\n**Example:** \`bounce: 0.65\``,
  collideBounds: `### \`collideBounds\`\nDetermines whether the object bounces against the logical edges of the scene window.\n\n**Accepts:** \`true\`, \`false\`\n**Example:** \`collideBounds: true\``,
};

export const namedColors = ["red", "green", "blue", "white", "black", "yellow", "cyan", "magenta", "orange"];

export const VALUE_DOCS: Record<string, string> = {
  "true": `### \`true\`\n**Type:** boolean\n\nRepresents a boolean true value.\n\n**Example:** \`loop: true\``,
  "false": `### \`false\`\n**Type:** boolean\n\nRepresents a boolean false value.\n\n**Example:** \`collideBounds: false\``,
  "indefinitely": `### \`indefinitely\`\n**Type:** duration\n\nA special duration keyword for \`physics\` blocks. Means the simulation runs forever with no time limit.\n\nOnly valid on a top-level \`physics\` block (not inside a \`sequence\`). An object using \`duration: indefinitely\` cannot have a \`sequence\` block, because the sequence can never activate.\n\n**Example:** \`duration: indefinitely\``,
  "contain": `### \`contain\`\n**Type:** sceneFit\n\nScales the scene to fit inside the preview window while preserving aspect ratio. The entire scene is visible, but there may be letterboxing.\n\n**Example:** \`sceneFit: contain\``,
  "cover": `### \`cover\`\n**Type:** sceneFit\n\nScales the scene to cover the entire preview window while preserving aspect ratio. The scene may be cropped.\n\n**Example:** \`sceneFit: cover\``,
  "fill": `### \`fill\`\n**Type:** sceneFit\n\nStretches the scene to exactly fill the preview window, ignoring aspect ratio.\n\n**Example:** \`sceneFit: fill\``,
  "none": `### \`none\`\n**Type:** sceneFit\n\nDisables scaling; the scene is displayed at its original size.\n\n**Example:** \`sceneFit: none\``,
  "linear": `### \`linear\`\n**Type:** easing\n\nConstant speed animation. No acceleration or deceleration.\n\n**Example:** \`easing: linear\``,
  "easeIn": `### \`easeIn\`\n**Type:** easing\n\nStarts slow and accelerates towards the end. Useful for objects leaving the screen.\n\n**Example:** \`easing: easeIn\``,
  "easeOut": `### \`easeOut\`\n**Type:** easing\n\nStarts fast and decelerates to a stop. Creates a natural landing effect.\n\n**Example:** \`easing: easeOut\``,
  "easeInOut": `### \`easeInOut\`\n**Type:** easing\n\nStarts slow, speeds up, then slows down. Gives a smooth, professional feel.\n\n**Example:** \`easing: easeInOut\``,
};